apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  image:
    registry: "docker.io/apicurio"
    version: "latest"
  configuration:
    persistence: "mem"
  deployment:
    route: "registry.example.com"
