[#apicurio-registry-operator]
= Apicurio Registry Operator

[#requirements]
== Requirements

* Docker
* https://github.com/golang/go[go] (1.14+, with `export GO111MODULE='on'`), and `$GOPATH` and `$GOROOT` set.
* https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md[Operator SDK] v1.4+
* A running Kubernetes, https://kubernetes.io/docs/tasks/tools/install-minikube/[Minikube], OpenShift, or Minishift deployment with system admin access.

[#quickstart]
== Quickstart

1. Prepare your Kubernetes cluster.
If you are using Minikube, run `minikube addons enable ingress`.

1. Choose a Docker registry where you can push operator images that you built during testing. e.g. `quay.io/foo`

1. Run `make build-reload OPERATOR_IMAGE_REPOSITORY="quay.io/foo"`.
This will build the operator image from scratch, push it into your registry, and deploy it in the `system` namespace in your cluster.
Run `make` without any parameters to get a help message.

1. To create a new Apicurio Registry deployment, the fastest way is to use in-memory persistence option and one of the example CRs:
`$ cat config/examples/resources/registry_v1_apicurioregistry.yaml | kubectl -n system apply -f -`

1. Verify that your Apicurio Registry deployment is healthy (for Minikube):
`$ kubectl -n system get ingress`
`$ curl -H "Host: example-apicurioregistry.system" http://$(minikube ip)/health`

1. Run `$ cat config/examples/resources/registry_v1_apicurioregistry.yaml | kubectl -n system delete -f -; make undeploy`
to remove the operator from your cluster.

NOTE: The in-memory deployment is not suitable for production.
We recommend using Kafka Streams persistence option for that.
See the contents of `./docs` for more information.

[#notes]
== Notes

Please create an issue on GitHub if you come across any problems.

You can find more documentation in `./docs`.
