apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: apicurio-registry-operator
  name: system # Remove?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-operator
  # namespace: system ???
  labels:
  # control-plane: apicurio-registry-operator ???
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 65532
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          name: apicurio-registry-operator
          image: quay.io/apicurio/apicurio-registry-operator:1.0.0-dev
          imagePullPolicy: Always
          env:
            - name: REGISTRY_VERSION
              value: "2.0.x"
            - name: REGISTRY_IMAGE_MEM
              value: "quay.io/apicurio/apicurio-registry-mem:latest-snapshot"
            - name: REGISTRY_IMAGE_STREAMS
              value: "quay.io/apicurio/apicurio-registry-streams:latest-snapshot"
            - name: REGISTRY_IMAGE_SQL
              value: "quay.io/apicurio/apicurio-registry-sql:latest-snapshot"
            - name: REGISTRY_IMAGE_INFINISPAN
              value: "quay.io/apicurio/apicurio-registry-infinispan:latest-snapshot"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "apicurio-registry-operator"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
