apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  image:
    registry: "docker.io/apicurio"
    version: "latest-snapshot"
  configuration:
    persistence: "streams"
    streams:
      bootstrapServers: "<service name>.<namespace>.svc:9092"
      # e.g. bootstrapServers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
      applicationId: "example-apicurioregistry"
  deployment:
    replicas: 2
    route: "registry.example.com"
