apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "jpa"
    dataSource:
      url: "jdbc:postgresql://<service name>.<namespace>.svc:5432/<database name>"
      # e.g. url: "jdbc:postgresql://acid-minimal-cluster.default.svc:5432/registry"
      userName: "postgres"
      password: "<password>"
      # ^ Optional
