
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - registry.apicur.io
  resources:
  - apicurioregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.apicur.io
  resources:
  - apicurioregistries/finalizers
  verbs:
  - update
- apiGroups:
  - registry.apicur.io
  resources:
  - apicurioregistries/status
  verbs:
  - get
  - patch
  - update
