# permissions for end users to edit apicurioregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurioregistry-editor-role
rules:
- apiGroups:
  - registry.apicur.io
  resources:
  - apicurioregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.apicur.io
  resources:
  - apicurioregistries/status
  verbs:
  - get
