kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apicurio-registry-operator
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-operator
    namespace: {NAMESPACE}
