apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurio-registry-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
