apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "mem"
  image:
    name: "docker.io/apicurio/apicurio-registry-mem:1.3.2.Final"
#   ^ IMPORTANT: This field is *deprecated* and may be removed in the future.
#     The operand images are specified using environment variables in the operator Deployment/DeploymentConfig resource.
