apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  image:
    name: "apicurio/apicurio-registry-streams:latest-release"
  configuration:
    persistence: "streams"
    streams:
      bootstrapServers: "<service name>.<namespace>.svc:9092"
      # e.g. bootstrapServers: "my-cluster-kafka-bootstrap.kafka.svc:9092"
      applicationId: "example-apicurioregistry"
      # ^ Optional
      # ...optional security configuration, using TLS or SCRAM
