package svc

const SVC_CLIENTS = "SVC_CLIENTS"
const SVC_CONFIGURATION = "SVC_CONFIGURATION"
const SVC_PATCHERS = "SVC_PATCHERS"
const SVC_CONTROLLER = "SVC_CONTROLLER"
const SVC_KUBE_FACTORY = "SVC_KUBE_FACTORY"
const SVC_OCP_FACTORY = "SVC_OCP_FACTORY"
const SVC_SCHEME = "SVC_SCHEME"
const SVC_NATIVE_CLIENT = "SVC_NATIVE_CLIENT"
const SVC_RESOURCE_CACHE = "SVC_RESOURCE_CACHE"
const SVC_ENV_CACHE = "SVC_ENV_CACHE"

