[id="registry-persistence-jpa"]
= Configuring Java Persistence API (PostgreSQL) storage

.Prerequisites
* You must have an OpenShift cluster with cluster administrator access.
* You must have already installed {operator} 
* You have a PostgreSQL database reachable from your OpenShift cluster. See xref:assembly-operator-installation.adoc[].

ifdef::service-registry[]
IMPORTANT: The PostgreSQL storage option is a https://access.redhat.com/support/offerings/techpreview[Technology Preview] feature and is currently not suitable for production environments.
endif::[]

.Procedure
. In the OpenShift Container Platform web console, log in with cluster administrator privileges.

. Change to the OpenShift project in which {registry} and your PostgreSQL Operator are installed.
For example, from the *Project* drop-down, select `my-project`.

ifdef::apicurio-registry[]
. Click *Installed Operators* > *{registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*.
endif::[]
ifdef::rh-service-registry[]
. Click *Installed Operators* > *Red Hat Integration - {registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*.
endif::[]

. Paste in the following `ApicurioRegistry` CR, and edit the values for the database `url` and credentials to match your environment:
+
[source,yaml]
----
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "jpa"
    dataSource:
      url: "jdbc:postgresql://SERVICE_NAME.NAMESPACE.svc:5432/"
      # e.g. url: "jdbc:postgresql://acid-minimal-cluster.my-project.svc:5432/"
      userName: "postgres"
      password: "PASSWORD"
      # ^ Optional
----

. Click *Create* and wait for the {registry} route to be created on OpenShift.

. Click *Networking* > *Route* to access the new route for the {registry} web console.

.Additional resources
* link:https://access.crunchydata.com/documentation/postgres-operator/4.5.0/quickstart/[Crunchy PostgreSQL Operator QuickStart]
