[id="registry-persistence-kafka-streams-tls"]
= Configuring Kafka Streams storage with TLS security

You can configure the {kafka-streams} Operator and {operator} to use an encrypted Transport Layer Security (TLS) connection.

.Prerequisites

* You must install the {operator} using the OperatorHub or command line.
* You must install the {kafka-streams} Operator or have Kafka accessible from your OpenShift cluster.

NOTE: This section assumes that the {kafka-streams} Operator is available, however you can use any Kafka deployment.
In that case, you must manually create the Openshift secrets that the {operator} expects.

.Procedure 

. In the OpenShift web console, click *Installed Operators*, select the *{kafka-streams}* Operator details, and then the *Kafka* tab. 

. Click *Create Kafka* to provision a new Kafka cluster for {registry} storage. 

. Configure the `authorization` and `tls` fields to use TLS authentication for the Kafka cluster, for example:
+
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: registry-example-streams-tls
spec:
  kafka:
    authorization:
      type: simple
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
----

. Click the *Kafka Topic* tab, and then *Create Kafka Topic* to create the required `global-id-topic`:
+
[source,yaml]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: global-id-topic
  labels:
    strimzi.io/cluster: my-cluster
  namespace: registry-example-streams-plain
spec:
  partitions: 2
  replicas: 1
  config:
    cleanup.policy: compact
----

. Change the topic name to `global-id-topic`, and optionally decrease the partition and replica count to minimum, which is sufficient for an example deployment.

. Perform the same steps to create the required `storage-topic` topic.

. Create a *Kafka User* resource to configure authentication and authorization for the {registry} user. For example, in the `spec` block, you can specify a user name in the `metadata` section or use the default `my-user`.
+
[source,yaml]
----
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: cluster
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
      - operation: All
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
----
+
NOTE: You must configure the authorization specifically for the topics and resources that the {registry} requires. This is a simple example.

. Click *Workloads* and then *Secrets* to find two secrets that {kafka-streams} creates for {registry} to connect to the Kafka cluster:
+
* `my-cluster-cluster-ca-cert` - contains the PKCS12 truststore for the Kafka cluster
* `my-user` - contains the user's keystore
+
NOTE: The name of the secret can vary based on your cluster or user name.

. If you create the secrets manually, they must contain the following key-value pairs:
+
* *my-cluster-ca-cert*
** `ca.p12` - truststore in PKCS12 format
** `ca.password` - truststore password
* *my-user*
** `user.p12` - keystore in PKCS12 format
** `user.password` - keystore password

. Configure the following example configuration to deploy the {registry}.
+
[source,yaml]
----
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "streams"
    streams:
      bootstrapServers: "my-cluster-kafka-bootstrap.registry-example-streams-tls.svc:9093"
      security:
        tls:
          keystoreSecretName: my-user
          truststoreSecretName: my-cluster-cluster-ca-cert
----

IMPORTANT: You must use a different `bootstrapServers` address than in the plain insecure use case. The address must support TLS connections and is found in the specified *Kafka* resource under the `type: tls` field.
