[id="registry-operator-quickstart"]
= Quickstart {operator} installation

You can quickly deploy the {operator} on the command line, without the Operator Lifecycle Manager, by using a downloaded set of installation files and example Custom Resource Definitions (CRDs). 

.Prerequisites

* You are logged into an OpenShift cluster with administrator access.
* You have the OpenShift `oc` command-line client installed. For more details, see the {LinkOCPCLIDocs}[{NameOCPCLIDocs}].

.Procedure

. Browse to link:{LinkRedHatIntegrationDownloads}[{NameRedHatIntegrationDownloads}], select the product version, and download the examples in the {registry} CRDs `.zip` file.

. Extract the downloaded CRDs `.zip` file and change to the `apicurio-registry-install-examples` directory.

. Create an OpenShift project for the {registry} installation, for example:
+
[source,bash]
----
NAMESPACE="apicurio-registry"
oc new-project "$NAMESPACE"
----

. Apply the example CRD specified in the `/install/install.yaml` file:
+
[source,bash]
----
cat install/install.yaml | sed "s/apicurio-registry-operator-namespace/$NAMESPACE/g" | oc apply -f -
----