[#manage-environment-variables]
= Managing Environment Variables

{operator} manages the most common configuration of {registry}, but there are some options that the user can
adjust manually. These are usually updated by setting an environment variable on the {registry} *DeploymentConfig* resource.
If the given configuration option is not available in the `ApicurioRegistry` CR, it is safe to use an environment variable to adjust it.

The following procedure can be used for this purpose:

Web UI

. Visit the *Installed Operators* tab, and select the *Red Hat Integration - {operator}*.
. In the *ApicurioRegistry* tab, click on the `ApicurioRegistry` CR for your {registry} deployment.
. In the main overview page, you'll see the *Deployment Name* section, which contains the name of the DeploymentConfig managed by the operator to deploy your {registry} instance.
. Find that *DeploymentConfig* by going to the *Workloads* > *Deployment Configs* in the left menu.
. Select the *DeploymentConfig* with the correct name, and switch to the *Environment* tab.
. You can add or modify your environment variable to the *Single values (env)* section.
. Click *Save* at the bottom.

Command Line Interface

. Select the project where {registry} is installed.
. Run `oc get apicurioregistry` to get the list of `ApicurioRegistry` CRs
. Run `oc describe` on the one representing the {registry} instance that you want to configure.
. You will see *Deployment Name* in the *status* section.
. Find that *DeploymentConfig* and edit it by running `oc edit`
. Add or modify the environment variable in the `spec.template.spec.containers[0].env` section.
