[id="registry-security-keycloak"]
= Securing {registry} API endpoints and web console using {keycloak}

The following procedure shows how to configure {registry} deployment to be protected by {keycloak}.

IMPORTANT: The example configuration in this procedure is intended only for development and testing.
In order to keep the procedure simple, it does not use HTTPS and other defenses recommended for a production environment.
Please follow the {keycloak} documentation for more details.

{registry} supports following user roles:

.Supported user roles
[%header,cols=2*]
|===
| Name | Capabilities

| `sr-admin`
| No restrictions

| `sr-developer`
| Can not modify global rules, perform import or export, and use `/admin` REST API endpoint

| `sr-readonly`
| Can not modify artifacts or rules
|===

NOTE: There is a related configuration option in `ApicurioRegistry` CRD that can be used to set the web console to read-only mode.
However, this configuration does not affect the REST API.

.Prerequisites
* You must have already installed the {operator}.
* You must install the {keycloak} Operator or have {keycloak} accessible from your OpenShift cluster.

.Procedure
. In the OpenShift web console, click *Installed Operators*, select the *{keycloak}* Operator details, and then the *Keycloak* tab.

. Click *Create Keycloak* to provision a new {keycloak} instance for securing a {registry} deployment. You can use the default value, for example:
+
[source,yaml]
----
include::{examplesdir}/keycloak/keycloak.yaml[]
----
+
NOTE: There is a known {keycloak} Operator issue https://issues.redhat.com/browse/KEYCLOAK-17532 which contains a workaround you may need, until it is fully resolved.

. When the cluster is ready, click *Networking* > *Route* to access the new route to the {keycloak} instance. Copy the auth URL value for later use when deploying {registry}.

. Click the *Keycloak Realm* tab, and then *Create Keycloak Realm* to create a `registry` example realm:
+
[source,yaml]
----
include::example$keycloak/keycloak_realm.yaml[]
----
+
This `KeycloakRealm` resource has to be customized with values suitable for your environment, if you are deploying to production.
You can also create and manage realms using the web console of {keycloak} instance.

. If your cluster does not have a valid HTTPS certificate configured, you can create the following HTTP `Service` and `Ingress` resources as a temporary workaround:
+
[source,yaml]
----
include::example$keycloak/keycloak_http_service.yaml[]
---
include::example$keycloak/keycloak_http_ingress.yaml[]
----
+
Modify the `host` value to create a route accessible for the {registry} user, and use it instead of the HTTPS route created by {keycloak} Operator.

. Select the *{operator}*, and in the *ApicurioRegistry* tab, click *Create ApicurioRegistry*, using the following example, but replace your values in the `keycloak` section.
+
[source,yaml]
----
include::example$keycloak/apicurioregistry_mem_keycloak_cr.yaml[]
----
