[id="registry-persistence-infinispan"]
= Configuring {registry} Infinispan storage
:parent: Configuration

The {registry} Infinispan storage option uses RAM on nodes where {registry} is deployed to store the data. This is achieved using an embedded Infinispan in-memory data grid, which also provides data replication between nodes. This configuration is simple, with an optional field to provide a name for the Infinispan cluster.

ifdef::service-registry[]
IMPORTANT: The Infinispan storage option is a https://access.redhat.com/support/offerings/techpreview[Technology Preview] feature and is currently not suitable for production environments.
endif::[]

.Prerequisites
* You must have an OpenShift cluster with cluster administrator access.
* You must have already installed the {operator}.

.Procedure

. In the OpenShift Container Platform web console, log in with cluster administrator privileges.

. Change to the OpenShift project in which {registry} is installed. For example, from the *Project* drop-down, select `my-project`.

ifdef::apicurio-registry[]
. Click *Installed Operators* > *{registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*.
endif::[]
ifdef::rh-service-registry[]
. Click *Installed Operators* > *Red Hat Integration - {registry}* > *ApicurioRegistry* > *Create ApicurioRegistry*.
endif::[]

. Use the following example `ApicurioRegistry` CR:

[source,yaml]
----
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry
spec:
  configuration:
    persistence: "infinispan"
    infinispan: # Currently, registry uses an embedded version of Infinispan
      clusterName: "example-apicurioregistry"
      # ^ Optional
----
