[id="manage-registry-environment-variables"]
= Managing {registry} environment variables

{operator} manages most common {registry} configuration, but there are some options that you can adjust manually. You can update these by setting an environment variable on the {registry} `Deployment` resource. If the specific configuration option is not available in the `ApicurioRegistry` CR, you can use an environment variable to adjust it.

.Procedure

OpenShift web console::

. Select the *Installed Operators* tab, and then the *{prodnamefull} - {operator}*.
. On the *Apicurio Registry* tab, click the `ApicurioRegistry` CR for your {registry} deployment.
. On the main overview page, view the `managedResources` section, which contains the name of the `Deployment` managed by the Operator to deploy your {registry} instance.
. Find that `Deployment` in the *Workloads* > *Deployments* in the left menu.
. Select the `Deployment` with the correct name, and select the *Environment* tab.
. You can add or modify your environment variable to the *Single values (env)* section.
. Click *Save* at the bottom.

OpenShift CLI::

. Select the project where {registry} is installed.
. Run `oc get apicurioregistry` to get the list of `ApicurioRegistry` CRs
. Run `oc describe` on the CR representing the {registry} instance that you want to configure.
. View the `managedResource` in the `status` section.
. Find that `Deployment` and enter `oc edit`.
. Add or modify the environment variable in the `spec.template.spec.containers[0].env` section.
