[id="registry-quickstart"]
= Quickstart {registry} deployment

To quickly create a new {registry} deployment, use the in-memory storage option,
which does not require an external storage to be configured as a prerequisite.

ifdef::apicurio-registry-operator-dev[]
NOTE: This procedure will deploy the latest released version of {operator}.
If you want to deploy the development version, visit https://github.com/Apicurio/apicurio-registry-operator/[{operator} GitHub repository].
endif::[]

.Prerequisites
* Ensure that the {operator} is already installed.

.Procedure
. Use a `$NAMESPACE` where the {operator} is deployed:
+
[source,bash]
----
export NAMESPACE="default"
----

. Create an `ApicurioRegistry` custom resource (CR):
+
[source,bash,subs="attributes"]
----
kubectl apply -f https://raw.githubusercontent.com/Apicurio/apicurio-registry-operator/{operator-version-latest-release-tag}/docs/modules/ROOT/examples/apicurioregistry_mem_cr.yaml -n $NAMESPACE
----
NOTE: If you want to deploy an older release of the Operator, follow the documentation for that version. +
If you are deploying to OpenShift, use `oc` with the same arguments.
+
.Example CR for in-memory storage
[source,yaml]
----
include::example$apicurioregistry_mem_cr.yaml[]
----
