[#backup-and-restore]
= Backup and Restore

The data stored by {registry} should be backed up regularly.
While the procedure is essentially simple, there are several ways to do it depending on the type of persistence backend and where it's running.

[#postgresql-backup-and-restore]
== PostgreSQL - SQL Dump

https://www.postgresql.org/docs/12/backup-dump.html[SQL Dump] is a simple procedure that works with any PostgreSQL installation.
It uses the https://www.postgresql.org/docs/12/app-pgdump.html[pg_dump] utility program to generate a file with SQL commands that can be used to recreate the database in the same state as it was at the time of the dump.

[#creating-the-dump]
=== Creating the Dump

pg_dump writes its result to the standard output and a common approach is to redirect the output to a file.

 $ pg_dump dbname > dumpfile

pg_dump is a regular PostgreSQL client application, therefore it can be executed from any remote host that has access to the database.
Like any other client, the operations it can perform are limited to the user permissions.

The database server pg_dump should connnect to is specified by the command line options `-h host` and `-p port`.
Client authentication can be done in many ways as described in https://www.postgresql.org/docs/12/client-authentication.html[Chapter 20] of the PostgreSQL documentation.

Large dump files can be reduced using a compression tool, such as gzip.

 $ pg_dump dbname | gzip > filename.gz

[#restoring-the-dump]
=== Restoring the Dump

Dump files created by pg_dump aren't restored with the same program, they are restored using `psql`.
Also, it's important to note the SQL dump doesn't include a command to create the database, so that needs to happen as a separate step before executing `psql`.

The usual commands to restore a SQL dump are:

 $ createdb -T template0 dbname
 $ psql dbname < dumpfile

Before restoring an SQL dump, all the users who own objects or were granted permissions on objects in the dumped database must already exist.

After restoring a backup, it is wise to run https://www.postgresql.org/docs/12/sql-analyze.html[ANALYZE] on each database so the query optimizer has useful statistics.
