[id="deploy-operator-cli"]
== Deploying {operator} using the command line

You can use the `kubectl` or `oc` CLI to deploy the {operator}.

To deploy the {operator}, you must create several types of resources in your cluster:

* _Service Account_, _Role_, and _Cluster Role_ - to configure permissions for the Operator.
* _Custom Resource Definition (CRD)_ - which defines resources that the Operator understands, and are created by users to provide configuration for {registry} deployment.
* _Deployment_ - to deploy the Operator Pod.

These resources are located in the `deploy` and `deploy/crds` directories. The resources are packaged into a single file so that you can deploy the latest development Operator version using a single command:

.Procedure
. Enter the following command to deploy the latest development Operator version:
[source,bash]
----
export NAMESPACE="default" &&
export GIT_REF="master" &&
curl -sSL "https://raw.githubusercontent.com/apicurio/apicurio-registry-operator/$GIT_REF/docs/install/install.yaml" | sed "s/{NAMESPACE}/$NAMESPACE/g" | kubectl apply -f -
----
+
You can modify the variables to deploy to a different namespace, or use a released version of the operator by selecting a git tag (0.0.3+).
+
If you are deploying to OpenShift, you can use `oc` with the same arguments.

. Enter the following commands to deploy the resources:
+
[source,bash]
----
export NAMESPACE="<target namespace>"
kubectl create -f ./deploy/service_account.yaml
kubectl create -f ./deploy/role.yaml
kubectl create -f ./deploy/role_binding.yaml
kubectl create -f ./deploy/cluster_role.yaml
cat ./deploy/cluster_role_binding.yaml | sed "s/{NAMESPACE}/$NAMESPACE/g" | kubectl apply -f -
kubectl create -f ./deploy/crds/apicur.io_apicurioregistries_crd.yaml
kubectl create -f ./deploy/operator.yaml
----

. You can create an `ApicurioRegistry` CR to instruct the Operator to deploy {registry}. For more details, see .

.Additional resources
* For more details on creating an `ApicurioRegistry` CR, see xref:assembly-operator-configuration[].
//Add back when link works?
//* For more details on building and deploying development versions of the Operator, see link:{{ site.baseurl }}{% link docs/Development.md %}[Development Documentation].
