[id="registry-persistence-mem"]
= Configuring {registry} In-Memory storage using CLI

The in-memory storage option uses RAM to store the data on nodes where {registry} is deployed, and it is the simplest persistence option to use.
The {operator} will deploy {registry} in this way if you do not provide any configuration in the `ApicurioRegistry` CR:

[source,yaml]
----
include::example$in-memory_cr.yaml[]
----

.Prerequisites
* You must have an OpenShift cluster with cluster administrator access.
* You must have already installed the {operator}.

.Procedure

. Deploy the example CR using following commands:
+
[source,bash,subs="attributes"]
----
export GIT_REF="{operator-version-tag}" &&
curl -sSL "https://raw.githubusercontent.com/apicurio/apicurio-registry-operator/$GIT_REF/docs/modules/ROOT/examples/in-memory_cr.yaml" | kubectl apply -f -
----

IMPORTANT: This persistence option does not support data distribution across {registry} nodes.
Therefore, it is only recommended for development environments using a single replica (`Pod`).
Use embedded Infinispan persistence option when deploying multiple replicas.
