[#liveness-and-readiness]
= Liveness and Readiness

{registry} provides readiness and liveness probes for OpenShift to ensure application health.
It is set up to use reasonable defaults, but in case users want to adjust them, the following is an overview of environment variables that can be used:

== Liveness

|===
| Name | Value Type | Description

| LIVENESS_ERROR_THRESHOLD
| positive integer
| Number of liveness errors that  can occur before the liveness probe fails.

| LIVENESS_COUNTER_RESET
| positive integer, seconds
| The period in which the _threshold_ number of errors  must occur, i.e.
if this value is 60 and the threshold is 1, the check fails  after two errors occur in 1 minute.

| LIVENESS_STATUS_RESET
| positive integer, seconds
| Number of seconds that must elapse without any more errors for the liveness probe to reset to _OK_ status.
_Note: Since OpenShift restarts the pod that fails the liveness check, this value (unlike readiness) does not actually affect what happens._

| LIVENESS_ERRORS_IGNORED
| comma-separated list of fully qualified exception class names
| List of errors that are ignored for liveness checking purposes.

|===

== Readiness

|===
| Name | Value Type | Description

| READINESS_ERROR_THRESHOLD
| positive integer
| Number of readiness errors that  can occur before the readiness probe fails.

| READINESS_COUNTER_RESET
| positive integer, seconds
| The period in which the _threshold_ number of errors  must occur, i.e.
if this value is 60 and the threshold is 1, the check fails  after two errors occur in 1 minute.

| READINESS_STATUS_RESET
| positive integer, seconds
| Number of seconds that must elapse without any more errors for the readiness probe to reset to _OK_ status.
_Note: _In practice, this means how long the pod remains in a not ready state until it returns to normal operation._

| READINESS_TIMEOUT
| positive integer, seconds
| The readiness system tracks the timeout of two operations: How long it takes for a storage request to complete, and how long it takes for an HTTP REST API request to return a response.
If the operation takes more time, it is counted as a readiness error. This value controls those timeouts.

|===

NOTE: Definitions: *Liveness Error* - the application cannot make progress, OpenShift will restart the failing pod.
*Readiness Error* - the application is not ready (e.g. it is overwhelmed by requests).
OpenShift will stop sending requests to the pod for the time the probe fails.
If other pods are OK, they will still receive requests.
