name: Apicurio Registry Operator - Build and publish from 0.x

on:
  push:
    branches:
      - 0.x

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REGISTRY_ORG: apicurio

jobs:
  main:
    name: Build and publish from master
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@master

      - name: Setup the environment
        run: ./.github/scripts/setup.sh

      - name: Setup Docker
        run: |
          docker login -u "${{ secrets.REGISTRY_USER }}" -p "${{ secrets.REGISTRY_SECRET }}" "${IMAGE_REGISTRY}"

      - name: Build
        id: build
        run: ./build.sh build -r "${IMAGE_REGISTRY}/${IMAGE_REGISTRY_ORG}"

      - name: Publish
        id: publish
        run: ./build.sh push -r "${IMAGE_REGISTRY}/${IMAGE_REGISTRY_ORG}" --latest

      - name: Test
        id: test
        run: ./.github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collect_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts