name: Validate Conventional Commits
on: [ pull_request ]

jobs:
  validate-conventional-commits:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
