name: verify api-model
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-project:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          architecture: x64

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Project
        run: cd api-model && ./mvnw clean install