
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apicurio-registry-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: apicurio-registry-operator
rules:
  - apiGroups: # OCP
      - route.openshift.io
      - apps.openshift.io
    resources:
      - routes
      - routes/custom-host
      - deploymentconfigs
    verbs:
      - '*'
  - apiGroups:
      - ""
      - "extensions" # ingress
      - route.openshift.io
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - ingresses # ingress
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - apicurio-registry-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - apicur.io
    resources:
      - '*'
    verbs:
      - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-operator
subjects:
- kind: ServiceAccount
  name: apicurio-registry-operator
roleRef:
  kind: Role
  name: apicurio-registry-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurio-registry-operator
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get
  - apiGroups:
      - apicur.io
    resources:
      - apicurioregistries
    verbs:
      - "*"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apicurio-registry-operator
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-operator
    namespace: apicurio-registry

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apicurioregistries.apicur.io
spec:
  group: apicur.io
  names:
    kind: ApicurioRegistry
    listKind: ApicurioRegistryList
    plural: apicurioregistries
    singular: apicurioregistry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ApicurioRegistry is the Schema for the apicurioregistries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApicurioRegistrySpec defines the desired state of ApicurioRegistry
          properties:
            configuration:
              properties:
                dataSource:
                  properties:
                    password:
                      type: string
                    url:
                      type: string
                    userName:
                      type: string
                  type: object
                infinispan:
                  properties:
                    clusterName:
                      type: string
                  type: object
                kafka:
                  properties:
                    bootstrapServers:
                      type: string
                  type: object
                logLevel:
                  type: string
                persistence:
                  enum:
                  - mem
                  - jpa
                  - kafka
                  - streams
                  - infinispan
                  type: string
                streams:
                  properties:
                    applicationId:
                      type: string
                    applicationServerPort:
                      type: string
                    bootstrapServers:
                      type: string
                    security:
                      properties:
                        scram:
                          properties:
                            mechanism:
                              type: string
                            passwordSecretName:
                              type: string
                            truststoreSecretName:
                              type: string
                            user:
                              type: string
                          type: object
                        tls:
                          properties:
                            keystoreSecretName:
                              type: string
                            truststoreSecretName:
                              type: string
                          type: object
                      type: object
                  type: object
                ui:
                  properties:
                    readOnly:
                      type: boolean
                  type: object
              type: object
            deployment:
              properties:
                host:
                  type: string
                replicas:
                  format: int32
                  type: integer
              type: object
            image:
              properties:
                name:
                  description: Registry string `json:"registry,omitempty"` Version  string
                    `json:"version,omitempty"` Override string `json:"override,omitempty"`
                  type: string
              type: object
          type: object
        status:
          description: ApicurioRegistryStatus defines the observed state of ApicurioRegistry
          properties:
            deploymentName:
              type: string
            host:
              type: string
            image:
              type: string
            ingressName:
              type: string
            replicaCount:
              format: int32
              type: integer
            serviceName:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurio-registry-operator
  template:
    metadata:
      labels:
        name: apicurio-registry-operator
    spec:
      serviceAccountName: apicurio-registry-operator
      containers:
        - name: apicurio-registry-operator
          # Replace this with the built image name
          image: quay.io/akieling/apicurio-registry-operator:0.0.3-dev # replaced {OPERATOR_IMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "4m"
            requests:
              memory: "32Mi"
              cpu: "2m"
          env:
            - name:  REGISTRY_IMAGE_MEM
              value: "docker.io/apicurio/apicurio-registry-mem:1.2.2.Final"
            - name:  REGISTRY_IMAGE_KAFKA
              value: "docker.io/apicurio/apicurio-registry-kafka:1.2.2.Final"
            - name:  REGISTRY_IMAGE_STREAMS
              value: "docker.io/apicurio/apicurio-registry-streams:1.2.2.Final"
            - name:  REGISTRY_IMAGE_JPA
              value: "docker.io/apicurio/apicurio-registry-jpa:1.2.2.Final"
            - name:  REGISTRY_IMAGE_INFINISPAN
              value: "docker.io/apicurio/apicurio-registry-infinispan:1.2.2.Final"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurio-registry-operator"

