
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apicurio-registry-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: apicurio-registry-operator
rules:
  - apiGroups:
      - ""
      - "extensions" # ingress
      - route.openshift.io
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - ingresses # ingress
      - routes/custom-host
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - apicurio-registry-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - apicur.io
    resources:
      - '*'
    verbs:
      - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apicurio-registry-operator
subjects:
- kind: ServiceAccount
  name: apicurio-registry-operator
roleRef:
  kind: Role
  name: apicurio-registry-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apicurioregistries.apicur.io
spec:
  group: apicur.io
  names:
    kind: ApicurioRegistry
    listKind: ApicurioRegistryList
    plural: apicurioregistries
    singular: apicurioregistry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configuration:
              properties:
                dataSource:
                  properties:
                    password:
                      type: string
                    url:
                      type: string
                    userName:
                      type: string
                  type: object
                kafka:
                  properties:
                    bootstrapServers:
                      type: string
                  type: object
                persistence:
                  enum:
                  - mem
                  - jpa
                  - kafka
                  - streams
                  type: string
                streams:
                  properties:
                    applicationId:
                      type: string
                    applicationServerPort:
                      type: string
                    bootstrapServers:
                      type: string
                  type: object
              type: object
            deployment:
              properties:
                replicas:
                  format: int32
                  type: integer
                resources:
                  properties:
                    cpu:
                      properties:
                        limit:
                          type: string
                        requests:
                          type: string
                      type: object
                    memory:
                      properties:
                        limit:
                          type: string
                        requests:
                          type: string
                      type: object
                  type: object
                route:
                  type: string
              type: object
            image:
              properties:
                override:
                  type: string
                registry:
                  type: string
                version:
                  type: string
              type: object
          type: object
        status:
          properties:
            deploymentName:
              type: string
            image:
              type: string
            ingressName:
              type: string
            replicaCount:
              format: int32
              type: integer
            route:
              type: string
            serviceName:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apicurio-registry-operator
  template:
    metadata:
      labels:
        name: apicurio-registry-operator
    spec:
      serviceAccountName: apicurio-registry-operator
      containers:
        - name: apicurio-registry-operator
          # Replace this with the built image name
          image: apicurio/apicurio-registry-operator:0.0.1-dev # replaced {OPERATOR_IMAGE}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "apicurio-registry-operator"

